# Generated by Django 5.2.5 on 2025-08-25 04:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='default_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_time',
            field=models.TimeField(null=True),
        ),
    ]
